import * as fs from 'fs';
import * as path from 'path';

/** Generate a unique string to avoid name collisions */
export function uniqueSuffix(): string {
  return Date.now().toString(36).toUpperCase();
}

/** Build a unique bot/form name */
export function uniqueName(prefix: string): string {
  return `${prefix}_${uniqueSuffix()}`;
}

/** Credentials from environment variables */
export const credentials = {
  username: process.env.USERNAME || 'rakshuvarshu216@gmail.com',
  password: process.env.PASSWORD || 'your_password_here',
};

/** Ensure the test upload fixture file exists */
export function ensureUploadFile(filename = 'sample-upload.txt'): string {
  const dir      = path.resolve(__dirname, '../fixtures');
  const filePath = path.join(dir, filename);

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(
      filePath,
      'This is a sample file for Automation Anywhere upload testing.\nGenerated by Playwright test suite.'
    );
  }

  return filePath;
}
